/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7yCx6k5jIze
 */
import { Avatar } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Component() {
  return (
    <main className="w-full h-full flex flex-col items-center justify-center p-6 gap-6">
      <h1 className="text-3xl font-bold text-center">Ideal Type World Cup</h1>
      <p className="text-center text-gray-500 mb-4">Click an option to progress to the next round.</p>
      <section className="grid grid-cols-2 gap-4">
        <Card className="flex flex-col items-center p-4 ring-4 ring-purple-500">
          <CardHeader>
            <Avatar className="w-20 h-20 mb-2" src="/placeholder.svg?height=100&width=100" />
            <Badge>Option 1</Badge>
          </CardHeader>
          <CardContent>
            <Button>Choose</Button>
          </CardContent>
        </Card>
        <Card className="flex flex-col items-center p-4 ring-4 ring-yellow-500">
          <CardHeader>
            <Avatar className="w-20 h-20 mb-2" src="/placeholder.svg?height=100&width=100" />
            <Badge>Option 2</Badge>
          </CardHeader>
          <CardContent>
            <Button>Choose</Button>
          </CardContent>
        </Card>
      </section>
      <Link className="underline mt-8" href="#">
        Proceed to the next round
      </Link>
    </main>
  )
}
